### ISSUE TITLE
Line color did not change when button is clicked

### ISSUE THREAD

**Issue by beajco** [Awalz/SwiftyDraw#12]
Hello! Sorry i dont know if this is an issue, or im just wrong on using it (sorry, im new at ios dev)

    @IBAction func markerButtonPressed(_ sender: Any) {
        drawView.brush.color = .red
        drawView.brush = Brush.thick
     }

The problem is that when I clicked the button, it doesn't change the color of the line.

![screen shot 2018-11-28 at 4 35 39 pm](https://user-images.githubusercontent.com/38550296/49139036-bcb63080-f32b-11e8-8d56-e3e9b9f0684c.png)

**Comment by beajco** [comment]
Ohh. Im just wrong on using it hehe
I should declare first the brush type before the color... because it overlaps.. Im sorry

**Comment by LinusGeffarth** [comment]
Correct! Glad you were able to fix it yourself

**Comment by beajco** [comment]
Hi sir! I have another problem. Could you help me?

**Comment by beajco** [comment]
I already open a new issue sir. Thanks a lot!
