### ISSUE TITLE
SwiftyDrawView(frame: X.frame)

### ISSUE THREAD

**Issue by beajco** [Awalz/SwiftyDraw#14]
Hi sir. Im sorry if I disturb you. But this what problem I encountered and I don't know if this relates to your pod.

**This view with grey background is my sketch view (a view inside view controller)**

![screen shot 2018-12-03 at 1 41 35 pm](https://user-images.githubusercontent.com/38550296/49411585-6cfcbc80-f7a4-11e8-99a2-c60adbdcd7e9.png)

****
![screen shot 2018-12-03 at 1 44 15 pm](https://user-images.githubusercontent.com/38550296/49411615-8271e680-f7a4-11e8-8e35-b3ade6195ebc.png)

**The problem here is that when I draw it overlaps to my sketchview, and i can't draw in the upper portion of the sketchview (please just look at the screenshot)**
![47394805_2159346874124117_4969836847250276352_n](https://user-images.githubusercontent.com/38550296/49411729-ff9d5b80-f7a4-11e8-8242-c0aec5ba0853.jpg)

**Comment by beajco** [comment]
![screen shot 2018-12-04 at 11 17 25 am](https://user-images.githubusercontent.com/38550296/49416868-78f17a00-f7b6-11e8-89d1-daf6663e695e.png)

Tried to run on Ipad simulator and this is the result

**Comment by LinusGeffarth** [comment]
No worries, you're not disturbing!

It looks like you're assigning a wrong frame to `drawView`. You should change:

    drawView = SwiftyDrawView(frame: sketchView.frame)

to:

    drawView = SwiftyDrawView(frame: sketchView.bounds)

---

Why exactly are you creating a new `drawView`? You could just use `sketchView` instead. 

I suggest you change:

    @IBOutlet wek var sketchView: UIView!

to:

    @IBOutlet wek var sketchView: SwiftyDrawView!

and assign the class in the storyboard.  
Then, remove:

    var drawView = SwiftyDrawView()

and:

    drawView = SwiftyDrawView(frame: sketchView.frame)
    sketchView.addSubview(drawView)

**Comment by beajco** [comment]
Problem Solve.
Thankyou bro! Godbless
