### ISSUE TITLE
How to save drawing as an image?

### ISSUE THREAD

**Issue by MRxGAM3R** [Awalz/SwiftyDraw#18]
Is there a way to convert the drawing of a SwiftyDraw view to a UIImage? Is there like a property I can access like `drawView.image` or `drawView.saveImage()`, or some other method by accessing its contents (I know there a lines property) and converting this into a UIImage? Thanks in advance.

**Comment by LinusGeffarth** [comment]
Hey @MRxGAM3R!
This is a feature I thought about implementing in the library, but figured it's out of the main scope, just like #17.

In my app, I did the following to get the drawing:

```swift
extension UIView {
    func screenshot() -> UIImage? {
        UIGraphicsBeginImageContextWithOptions(bounds.size, false, 0)
        defer { UIGraphicsEndImageContext() }
        drawHierarchy(in: bounds, afterScreenUpdates: true)
        return UIGraphicsGetImageFromCurrentImageContext()
    }
}
```

Then, you could just do:

```swift
let image = drawView.screenshot()
```
