### ISSUE TITLE
Change Line Colour

### ISSUE THREAD

**Issue by Andriyas123** [Awalz/SwiftyDraw#2]
Andrew, hello!

Just a quick question - I am trying to change colour of a line, however, whenever I press on a button Xcode throws a breakpoint and says - "unexpectedly found nil while unwrapping an Optional value" on a line of `drawView.lineColor= button.color` 

This error is always pretty easy to solve but now I cannot find a solution to it... Here is my piece of code:

class PhotoViewController: UIViewController, SwiftyDrawViewDelegate {
    
    private var backgroundImage: UIImage?
    
    var drawView : SwiftyDrawView!
    
    var cancelButton: UIButton!
    var shareButton: UIButton!
    var drawButton: UIButton!
    var saveButton: UIButton!
    var doneButton: UIButton!
    
    var redButton : ColorButton!

    init(image: UIImage) {
        self.backgroundImage = image
        super.init(nibName: nil, bundle: nil)
    }
    
    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()

        self.view.backgroundColor = UIColor.gray
        let backgroundImageView = UIImageView(frame: view.frame)
        backgroundImageView.contentMode = .scaleAspectFill
        backgroundImageView.image = backgroundImage
        view.addSubview(backgroundImageView)
        addButtons()
    }
    
    func addButtons() {
        
        cancelButton = UIButton(frame: CGRect(x: 10.0, y: 10.0, width: 50.0, height: 50.0))
        cancelButton.showsTouchWhenHighlighted = true
        cancelButton.setImage(#imageLiteral(resourceName: "Close"), for: UIControlState())
        cancelButton.addTarget(self, action: #selector(cancel), for: .touchUpInside)
        view.addSubview(cancelButton)
        
        saveButton = UIButton (frame: CGRect(x: 16.0, y: 503.0, width: 50, height: 50))
        saveButton.showsTouchWhenHighlighted = true
        saveButton.setImage(#imageLiteral(resourceName: "Save"), for: UIControlState())
        saveButton.addTarget(self, action: #selector(save), for: .touchUpInside)
        view.addSubview(saveButton)
        
        shareButton = UIButton (frame: CGRect(x: 240.0, y: 484.0, width: 60, height: 60))
        shareButton.showsTouchWhenHighlighted = true
        shareButton.setImage(#imageLiteral(resourceName: "Share"), for: UIControlState())
        shareButton.addTarget(self, action: #selector(share), for: .touchUpInside)
        view.addSubview(shareButton)
        
        drawButton = UIButton (frame: CGRect(x: 260.0, y: 10.0, width: 50, height: 50))
        drawButton.showsTouchWhenHighlighted = true
        drawButton.setImage(#imageLiteral(resourceName: "Draw"), for: UIControlState())
        drawButton.addTarget(self, action: #selector(draw), for: .touchUpInside)
        view.addSubview(drawButton)
        
    }
    
    func draw() {
        
        let drawView = SwiftyDrawView(frame: self.view.frame)
        drawView.delegate = self
        self.view.addSubview(drawView)
        
        let cancelButton = UIButton(frame: CGRect(x: 10.0, y: 10.0, width: 50.0, height: 50.0))
        cancelButton.showsTouchWhenHighlighted = true
        cancelButton.setImage(#imageLiteral(resourceName: "Close"), for: UIControlState())
        cancelButton.addTarget(self, action: #selector(cancel), for: .touchUpInside)
        view.addSubview(cancelButton)
        
        let doneButton = UIButton(frame: CGRect(x: 260.0, y: 10.0, width: 50.0, height: 50.0))
        doneButton.showsTouchWhenHighlighted = true
        doneButton.setImage(#imageLiteral(resourceName: "Done"), for: UIControlState())
        doneButton.addTarget(self, action: #selector(cancel), for: .touchUpInside)
        view.addSubview(doneButton)
        
        let redButton = ColorButton(frame: CGRect(x: 10, y: self.view.frame.height - 50, width: 40, height: 40), color: UIColor.red)
        redButton.showsTouchWhenHighlighted = true
        redButton.addTarget(self, action: #selector(colorButtonPressed(button:)), for: .touchUpInside)
        self.view.addSubview(redButton)
        
        UIView.animate(withDuration: 0.1, animations: {
            self.cancelButton.alpha = 0.0
            self.shareButton.alpha = 0.0
            self.saveButton.alpha = 0.0
            self.drawButton.alpha = 0.0
        })
    }
    
    func colorButtonPressed(button: ColorButton) {
        drawView.lineColor = button.color
    }
    
    func SwiftyDrawDidBeginDrawing(view: SwiftyDrawView) {
    }
    
    func SwiftyDrawIsDrawing(view: SwiftyDrawView) {
    }
    
    func SwiftyDrawDidFinishDrawing(view: SwiftyDrawView) {
    }
    
    func SwiftyDrawDidCancelDrawing(view: SwiftyDrawView) {
    }

Also, what would be your advice on merging background image with the drawing?

Thank you, Andrew!

**Comment by Awalz** [comment]
What is the source code for ColorButton?

**Comment by Andriyas123** [comment]
Andrew, this one: 

class ColorButton: UIButton {

    var color: UIColor
    
    init(frame: CGRect, color: UIColor) {
        self.color = color
        super.init(frame: frame)
        self.layer.cornerRadius = 0.5 * frame.size.width
        self.layer.borderColor = UIColor.black.cgColor
        self.layer.borderWidth = 1.0
        self.clipsToBounds = true
        self.backgroundColor = color
    }
    
    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
}`

The same error happened to undo and delete, though...

**Comment by Andriyas123** [comment]
Problem has been solved. In func draw(), I just had to delete let in drawView. Thank you!
