### ISSUE TITLE
How can i draw when zoom the view

### ISSUE THREAD

**Issue by ashokt** [Awalz/SwiftyDraw#26]

**Comment by LinusGeffarth** [comment]
@ashokt sorry for the late response. Zooming isn't a part of the SwiftyDraw library, but you can easily develop such a functionality yourself. Just place your `swiftyDrawView` inside a content view of a scroll view and then set the min & max zoom levels. And you're done!

**Comment by ashokt** [comment]
> @ashokt sorry for the late response. Zooming isn't a part of the SwiftyDraw library, but you can easily develop such a functionality yourself. Just place your `swiftyDrawView` inside a content view of a scroll view and then set the min & max zoom levels. And you're done!

Thanks for reply
I implemented the same way
