### ISSUE TITLE
How to draw with  Caligraphy brush type

### ISSUE THREAD

**Issue by bhaveshbc** [Awalz/SwiftyDraw#27]
I want to draw with calligraphy brush. I know how to achieve this with Context but not Abel with CGMutablePath.

![TQ1](https://user-images.githubusercontent.com/26791435/61171252-9b404700-a592-11e9-856d-23d80896bbc5.png)

**Comment by bhaveshbc** [comment]
Any Update?

**Comment by LinusGeffarth** [comment]
@bhaveshbc sorry forgot to respond, but saw your email now. We don't currently have that functionality implemented. SwiftyDraw is suitable for hand-writing, not for drawings.
If you find a way to implement this, please share it with us so we can merge it into the library :)

**Comment by bhaveshbc** [comment]
Thanks for your reply.
Yes I will create pull request if I’ll find any solution.
