### ISSUE TITLE
Add new version tag to master

### ISSUE THREAD

**Issue by whoover** [Awalz/SwiftyDraw#36]
Could you add new version tag and update version in pod file to make latest updates available? Thnx

**Comment by LinusGeffarth** [comment]
Yes, will update tonight! 🤞

**Comment by LinusGeffarth** [comment]
There it is 😊 @whoover 

<img width="324" alt="Bildschirmfoto 2020-03-24 um 08 53 11" src="https://user-images.githubusercontent.com/9455439/77401268-e6ab2600-6dac-11ea-9a66-847a6f229119.png">
