### ISSUE TITLE
Interested in the sample rate

### ISSUE THREAD

**Issue by karunyas** [Awalz/SwiftyDraw#38]
Hi,

Love this framework! Quick question, is there a way to know the sample rate of touches it picks up or adjust that rate? Thanks!!

Karunya

**Comment by LinusGeffarth** [comment]
H @karunyas!
What do you mean by _sample rate_?

**Comment by karunyas** [comment]
I was wondering how often Swifty draw records the touches while i'm continuously drawing a stroke? Like once every 10 ms, or something like that?

**Comment by LinusGeffarth** [comment]
We're using UIKit's default `touchesMoved` method to track drawing. So your question is probably about iOS in general, not related to SwiftyDraw.
