### ISSUE TITLE
Value of type 'SwiftyDrawView' has no member of the following

### ISSUE THREAD

**Issue by chishing96** [Awalz/SwiftyDraw#39]
`Value of type 'SwiftyDrawView' has no member 'getCurrentPathArray'`
and
`Value of type 'SwiftyDrawView' has no member 'setCurrentPathArray'`

from this line of code
`if self.signature != nil {
            self.signatureCanvas.setCurrentPathArray((self.signature?.getCurrentPathArray())!)
        }`

SwiftyDraw 2.3
iOS 13.5
Xcode 11.5
Swift 4.2

**Comment by LinusGeffarth** [comment]
You need to use the `.display(_:)` method.

On another note, what are you trying to do? Your code doesn't look like a best practice, imho.
