### ISSUE TITLE
Feature Request - Eraser

### ISSUE THREAD

**Issue by ghazi256** [Awalz/SwiftyDraw#5]
Apart from Clear Canvas, can you add eraser functionality as well?

**Comment by BobDeKort** [comment]
You could get around this by just "drawing" the same color as the background and pretend its an eraser.
Hope this still helps.

**Comment by kidvicious** [comment]
this method does not work for drawing over image. Can you help?

**Comment by LinusGeffarth** [comment]
I second this request, would be awesome!

**Comment by LinusGeffarth** [comment]
added in commit 24da626
