### ISSUE TITLE
Update cocoapods

### ISSUE THREAD

**Issue by matthiasnagel** [Awalz/SwiftyDraw#9]
I love SwiftyDraw. Can you please update cocoapods to version 2.0?

**Comment by LinusGeffarth** [comment]
Hey! Even though I'm contributing to the library and have written the changes for 2.0, I have no idea how CocoaPods works and hence, can't really do this (which bugs me as well!).
I've asked @Awalz for support, not sure he's available, though.

**Comment by LinusGeffarth** [comment]
@matthiasnagel letting you know that I'm on it, will keep you posted...

**Comment by LinusGeffarth** [comment]
@matthiasnagel updated version on cocoapods
